### ISSUE TITLE
Compact serialization w/multiple recipients not failing as it should

### ISSUE THREAD

**Issue by drennalls** [simo5/jwcrypto#13]
Seems to be a typo in the jwe.JWE.serialize method (see https://github.com/simo5/jwcrypto/blob/master/jwcrypto/jwe.py#L619), 'recipiens' instead of 'recipients'  .. so when multiple recipients have been added to a JWE .serialize(compact=True) it isn't failing as it should.

**Comment by simo5** [comment]
Nice catch!
