### ISSUE TITLE
JWS signature header type mismatch

### ISSUE THREAD

**Issue by nicfit** [simo5/jwcrypto#17]
To pass a header to JWS.add_signature I need to encode it has a string otherwise an exception it raised:

```
header = {..}
jws.add_signature(key, header=header)
# Raises TypeError
jws.add_signature(key, header=json_encode(header))
# Sucess
```

This results in the signature contain the decoding header with in the JSM object.

When a 'verify' is performed the header is passed as is to _verify where json_decode(header) is called and the following error occurs:
```
InvalidJWSSignature: Verification failed for all signatures['Failed: [TypeError("the JSON object must be str, not \'dict\'",)]'] 
```
If I skip the decode in ```_verify`` the verify succeeds.  Should the string'ified header be added to the signature object?

**Comment by simo5** [comment]
You are right add_signature is buggy here is should assign json_encode()ed strings.

**Comment by simo5** [comment]
On a second look it is the other way around, add_signature() is correct, it's deserialize() and verify() that are wrongly storing a json_encoded dictionary in the unprotected header element.
RFC7515 prescribes an uncoded object and Appendix 7 shows an eaxmple whic is properly tested for in tests-cookbook.py

**Comment by nicfit** [comment]
Excellent, thanks for the quick fix.
