### ISSUE TITLE
export individual public or private key?

### ISSUE THREAD

**Issue by franks42** [simo5/jwcrypto#8]
When I generate a key-pair with:

    k = jwk.JWK(generate='EC', crv='P-256', use='enc', kid='9876543210')

I'd like to "export" the public key in json format to communicate it to other parties. My understanding from reading the example code and API was, that I could possibly do that with:

    pk = k.get_op_key('encrypt')
    pk_json = pk.export()

but that doesn't work: "AttributeError: '_EllipticCurvePublicKey' object has no attribute 'export'"

Couldn't find any explicit example of this in the test code. Maybe I am missing something?
Thanks for the help - Frank.

**Comment by simo5** [comment]
k.export_public() is not ok ?

**Comment by franks42** [comment]
k.export_public() is ok.

Thanks - should learn not to trust the doc and look at the code before asking Qs ;-)

**Comment by simo5** [comment]
If it is not doc-ed that's a bug ... indeed it is.

**Comment by simo5** [comment]
Reopening, will use to track doc bug.

**Comment by franks42** [comment]
Appreciate the near instant, real-time support!

**Comment by franks42** [comment]
Not sure if it's a bug, but the exported public key lost the kid-attribute that was set on the generated key-pair.

**Comment by simo5** [comment]
It's a bug.

**Comment by simo5** [comment]
Fixed with 9d52a18adc42e88373b8502709ec2f313478023f
Also the "stable" docs had export_public() documentation, but the default docs were going to the "latest" tag on readthedocs, but it is unclear why that tag had no documentation. Will investigate and fix that.
Thanks a lot for reporting these issues.
