### ISSUE TITLE
export symmetric key?

### ISSUE THREAD

**Issue by franks42** [simo5/jwcrypto#9]
Trying to find a way to export the symmetric key as jose-json after:

    sym_k = jwk.JWK(generate='oct', size=256, use='sig', kid = '24680')

sym_k.export() throws an exception:

    ...
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 2: invalid continuation byte
    ...

while the sym_k.get_op_key('sign') seems to return the key's random byte-array.

Any advise?

**Comment by franks42** [comment]
The following method-snippet comes from the class JWK:

    def _generate_oct(self, params):
        size = 128
        if 'size' in params:
            size = params['size']
            del params['size']
        key = os.urandom(size // 8)
        params['kty'] = 'oct'
        #params['k'] = key
        params['k'] = base64url_encode(key)
        self.import_key(**params)

Note that the original code assigned the binary array "key" directly to params['k'], which caused the exception to fail on non-base64 bytes.
When I encode the key first to base64 and then assign it to the params['k'], then it seems to work... (as in the above code-snippet).
The tests are still ok, but they do not really test for the generation of symmetric keys inside of the constructor.
Not sure if this code change will do the trick as I'm not very familiar with the code - hopefully it will point you in the right direction.

**Comment by simo5** [comment]
Thanks for the report, should be fixed now.
